# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SugarToolsDialog
                                 A QGIS plugin
 Aqueological tools for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by PSIG
        email                : geraldo@servus.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.core import Qgis
from qgis.gui import QgsFileWidget
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

import os

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'sugar_tools_dialog.ui'))


class SugarToolsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SugarToolsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Set QgsMapComboBox filters
        self.blocks_polygon_layer.setFilters(Qgis.LayerFilter.PolygonLayer)
        self.blocks_lines_layer.setFilters(Qgis.LayerFilter.LineLayer)
        self.blocks_3d_layer.setFilters(Qgis.LayerFilter.PolygonLayer)

        self.extract_table.setFilters(Qgis.LayerFilter.NoGeometry)
        self.extract_polygon_layer.setFilters(Qgis.LayerFilter.PolygonLayer)
        self.extract_lines_layer.setFilters(Qgis.LayerFilter.LineLayer)
        self.extract_3d_layer.setFilters(Qgis.LayerFilter.PolygonLayer)

        self.structures_gpkg_3d.setFilter("GeoPackage files (*.gpkg)")